Improved ask for experiment.
famura/SimuRLacra pull request #32
Opened 2021-04-07 18:28 UTC by fdamken

* Added SLURM ID to `extra_info` from environment variables.
* Added more information to the experiments.
* Added possibility to show specific hyper-parameters.
* Implemented this to all calls of `ask_for_experiment(..)`.

2021-04-07 18:29 UTC, fdamken commented
The previous PR #25 got really bloated after rebasing famura/master onto the branch, hence I created a new PR.

2021-04-08 06:41 UTC, famura requested changes

2021-04-08 06:41 UTC, famura commented on Pyrado/pyrado/utils/data_types.py
> +    d: dict, path: str, default: typing.Optional[T] = None, default_for_last_layer_only: bool = False
this function needs a doc sting

2021-04-08 06:41 UTC, famura commented on Pyrado/pyrado/utils/input_output.py
> +T = typing.TypeVar("T")
import TypeVar with a from statement like the other classes from typing

2021-04-08 06:41 UTC, famura commented on Pyrado/pyrado/utils/input_output.py
> +import typing
see coment below

2021-04-08 06:41 UTC, famura commented on Pyrado/scripts/evaluation/eval_policies_domain_grid_1d.py
> +    if args.env_name is None:
I don't liek this if-else block. Let's stick to one of them (I think the if-part is better). remove the print statement

2021-04-08 06:41 UTC, famura commented on Pyrado/scripts/evaluation/eval_policies_domain_grid_1d.py
> -    elif args.env_name in [QCartPoleStabSim.name, QCartPoleSwingUpSim.name]:
followup changes due to comment above

2021-04-08 06:41 UTC, famura commented on Pyrado/pyrado/utils/data_types.py
> +import typing
get rid off this one

2021-04-08 06:41 UTC, famura commented on Pyrado/pyrado/utils/data_types.py
> +T = typing.TypeVar("T")
import TypeVar with from statement

2021-04-08 06:41 UTC, famura commented on Pyrado/pyrado/logger/experiment.py
> +    :param show_hparams: Load the hyperparams file and show the parameters in this list. Sub-dicts can be separated with a dot.
start lower case "l"

2021-04-08 06:41 UTC, famura commented on Pyrado/pyrado/logger/experiment.py
> +    latest_only: bool = False, max_display: int = 10, show_hparams: Optional[List[str]] = None
please reaname show_hparams since the name suggests that this is a boolian. how about hparam_list?

2021-04-08 06:41 UTC, famura commented on Pyrado/pyrado/logger/experiment.py
>      """ Setup a new experiment for recording. """
the docsting must explain every arument (:param: ... and optionally :return: ...)

2021-04-08 06:41 UTC, famura commented on Pyrado/pyrado/logger/experiment.py
> +    show_hparams: Optional[List[str]] = None, show_extra_info: bool = True
the docsting must explain every arument (:param: ... and optionally :return: ...)

2021-04-08 06:41 UTC, famura commented on Pyrado/pyrado/logger/experiment.py
> +    include_slurm_id: bool = True,
Optional[bool] = True

2021-04-08 06:41 UTC, famura commented on Pyrado/pyrado/logger/experiment.py
> +    base_dir: str = pyrado.TEMP_DIR,
plase also add Optional[] here

2021-04-13 17:40 UTC, merged