Added isort for import ordering.
famura/SimuRLacra pull request #37
Opened 2021-04-18 15:17 UTC by fdamken

[![order](https://media.giphy.com/media/tJMVcTfzDdL1pOGxlk/giphy.gif)]

2021-04-18 15:33 UTC, famura commented
Honestly, I don't like the way isort sorts.
![image](https://user-images.githubusercontent.com/37794142/115151210-2efa4d80-a06c-11eb-8441-6cfaa0ace32c.png)

2021-04-18 15:34 UTC, famura commented
Plus, I think this is incompatible with black.

2021-04-18 15:35 UTC, fdamken commented
> Honestly, I don't like the way isort sorts.
> ![image](https://user-images.githubusercontent.com/37794142/115151210-2efa4d80-a06c-11eb-8441-6cfaa0ace32c.png)

It's highly configurable and I did not expect you to like it on the first try.

2021-04-18 15:35 UTC, fdamken commented
> Plus, the result is incompatible with black.

It can be made compatible, just a configuration thing, see e.g. https://pycqa.github.io/isort/docs/configuration/black_compatibility/

2021-04-18 15:37 UTC, famura commented
Then we should make it compatible with black **and** match the existing style.

2021-04-18 15:39 UTC, miterion commented
> Honestly, I don't like the way isort sorts.
> ![image](https://user-images.githubusercontent.com/37794142/115151210-2efa4d80-a06c-11eb-8441-6cfaa0ace32c.png)

The suggested order is the one suggested by PEP-8 and kind of the industry standard in python: First standard lib, then external libraries, than internal stuff.

Are you sure you want to deviate from this?

2021-04-18 16:16 UTC, famura commented
You are right, the order is fine. I guess, I was just turned off by the black incompatibility and the extra line.

2021-04-18 16:18 UTC, famura commented
Please also run isort once for the Pyrado folder and the setup_deps.py file and the RcsPySim/setup.py file and verify that it works with Black

2021-04-18 16:18 UTC, famura commented
This way, we have it all good and it passes its workflow test

2021-04-18 16:18 UTC, fdamken commented
> Please also run isort once for the Pyrado folder and the setup_deps.py file and the RcsPySim/setup.py file and verify that it works with Black

I found the issue with Black compatibility, isort does not pick up the config file from the parent directory, I'll fix that,

2021-04-18 16:19 UTC, famura commented
> > Please also run isort once for the Pyrado folder and the setup_deps.py file and the RcsPySim/setup.py file and verify that it works with Black
> 
> I found the issue with Black compatibility, isort does not pick up the config file from the parent directory, I'll fix that,

Good. I also changed the order in which they run. That should solve it the easy way xD

2021-04-18 16:20 UTC, fdamken commented
> > > Please also run isort once for the Pyrado folder and the setup_deps.py file and the RcsPySim/setup.py file and verify that it works with Black
> > 
> > 
> > I found the issue with Black compatibility, isort does not pick up the config file from the parent directory, I'll fix that,
> 
> Good. I also changed the order in which they run. That should solve it the easy way xD

There's a small line between easy and hacky :P

2021-04-18 16:22 UTC, famura commented
Please also add isort to the pip install command in the docker file. Then we can remove the `pip install isort` from the github action

2021-04-18 16:23 UTC, famura commented
> > > > Please also run isort once for the Pyrado folder and the setup_deps.py file and the RcsPySim/setup.py file and verify that it works with Black
> > > 
> > > 
> > > I found the issue with Black compatibility, isort does not pick up the config file from the parent directory, I'll fix that,
> > 
> > 
> > Good. I also changed the order in which they run. That should solve it the easy way xD
> 
> There's a small line between easy and hacky :P

Happy to quote you on that one in the future :)
I guess it won't hurt if we do both solutions.

2021-04-18 16:26 UTC, famura requested changes

2021-04-18 16:26 UTC, famura commented on .github/workflows/lint.yml
> +      working-directory: .
well, then we don't need the whole `env` statement, right?

2021-04-18 16:26 UTC, famura commented on .github/workflows/lint.yml
> +        with:
lol, please change the order back.

2021-04-18 16:26 UTC, famura commented on .github/workflows/lint.yml
>          run: python -m pip install --upgrade isort
eventually remove this line

2021-04-18 16:31 UTC, famura commented
> docker

Ok

2021-04-18 16:32 UTC, famura commented
Sorry. Just the change in the Dockerfile, and the initial run are missing.

2021-04-18 16:49 UTC, fdamken commented
isort is now compatible with black, shall I push the reordered code?

2021-04-21 06:48 UTC, famura commented
I have an additional request. Could you please separate the three linting github actions into three different actions, such that they are ran independently? That would be great.

2021-04-21 16:38 UTC, famura approved these changes

2021-04-21 16:39 UTC, merged